uuid = "c32678a7-094b-4f9b-86f8-ff3a786cc9e4"
name = "Script Logger"
authors = ["Bob Swift"]
description = "This plugin provides a new script function `$logline()` to write entries to Picard's system log."
api = ['3.0']
license = "GPL-2.0"
license_url = "https://www.gnu.org/licenses/gpl-2.0.txt"
long_description = """
This plugin provides a new script function `$logline()` to write entries
to Picard's system log. By default, the log level is set at `Info`, but
any level can be used by providing the level as an optional second
parameter to the function.

The function is used as:

`$logline(text[,level])`

where `text` is the text to write to the log. The entry will be written
at log level `Info` by default, but this can be changed by specifying a
different level as an optional second parameter. Allowable log levels are:

- E (Error)
- W (Warning)
- I (Info)
- D (Debug)

If an unknown level is entered, the function will use the default `Info`
level.
"""
categories = [
    "scripting",
    "other",
]
homepage = "https://picard-plugins-user-guides.readthedocs.io/en/latest/script_logger/user_guide.html"
